### ISSUE TITLE
Deprecated package error when installing

### ISSUE THREAD

**Issue by jvg123** [sfdx-isv/fsc-demo-pack#9]
Got the following when running sfdx falcon:adk:install

```
ERROR running falcon:adk:install:  The step "Install FSC Managed Package" has failed. Its action, "install-package", returned the following error:
SfdxCliError: Installation of package 'Financial Services Cloud (Managed Package), Version 220.6' (04t1E000000y9ew) failed. Installation errors: 
1) Package(03380000000U1CP) AppExchange Package is Deprecated, Details: The AppExchange package has been deprecated and can no longer be installed.          Please try installing a newer version, or contact the package owner directly to resolve.
```

**Comment by jvg123** [comment]
Tried a manual install of the package from https://help.salesforce.com/s/articleView?id=000323341&type=1 and got:

```
% sfdx force:package:install --targetusername sfdx-isv_fsc-demo-pack_scratch-demo --package 04t1E000000jbFt --wait 10 --publishwait 10 --noprompt --json --loglevel error
ERROR:  Encountered errors installing the package!,Installation errors: 
1) (Alert__c.Claim__c) referenceTo value of 'Claim' does not resolve to a valid sObject type, Details: Alert__c.Claim__c: referenceTo value of 'Claim' does not resolve to a valid sObject type
2) (Alert__c.Insurance_Policy__c) referenceTo value of 'InsurancePolicy' does not resolve to a valid sObject type, Details: Alert__c.Insurance_Policy__c: referenceTo value of 'InsurancePolicy' does not resolve to a valid sObject type
3) (BillingStatement__c.InsurancePolicy__c) referenceTo value of 'InsurancePolicy' does not resolve to a valid sObject type, 
```

```
Details: BillingStatement__c.InsurancePolicy__c: referenceTo value of 'InsurancePolicy' does not resolve to a valid sObject type
{
  "status": 1,
  "name": "Error",
  "message": "Installation errors: \n1) (Alert__c.Claim__c) referenceTo value of 'Claim' does not resolve to a valid sObject type, Details: Alert__c.Claim__c: referenceTo value of 'Claim' does not resolve to a valid sObject type\n2) (Alert__c.Insurance_Policy__c) referenceTo value of 'InsurancePolicy' does not resolve to a valid sObject type, Details: Alert__c.Insurance_Policy__c: referenceTo value of 'InsurancePolicy' does not resolve to a valid sObject type\n3) (BillingStatement__c.InsurancePolicy__c) referenceTo value of 'InsurancePolicy' does not resolve to a valid sObject type, Details: BillingStatement__c.InsurancePolicy__c: referenceTo value of 'InsurancePolicy' does not resolve to a valid sObject type",
  "exitCode": 1,
  "commandName": "PackageInstallCommand",
  "stack": "Error: Installation errors: \n1) (Alert__c.Claim__c) referenceTo value of 'Claim' does not resolve to a valid sObject type, Details: Alert__c.Claim__c: referenceTo value of 'Claim' does not resolve to a valid sObject type\n2) (Alert__c.Insurance_Policy__c) referenceTo value of 'InsurancePolicy' does not resolve to a valid sObject type, Details: Alert__c.Insurance_Policy__c: referenceTo value of 'InsurancePolicy' does not resolve to a valid sObject type\n3) (BillingStatement__c.InsurancePolicy__c) referenceTo value of 'InsurancePolicy' does not resolve to a valid sObject type, Details: BillingStatement__c.InsurancePolicy__c: referenceTo value of 'InsurancePolicy' does not resolve to a valid sObject type\n    at /Users/xyz/.local/share/sfdx/client/7.94.3-a4e7c7955b/node_modules/salesforce-alm/dist/lib/package/packageInstallCommand.js:94:27\n    at tryCatcher (/Users/xyz/.local/share/sfdx/client/7.94.3-a4e7c7955b/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/Users/xyz/.local/share/sfdx/client/7.94.3-a4e7c7955b/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/Users/xyz/.local/share/sfdx/client/7.94.3-a4e7c7955b/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/Users/xyz/.local/share/sfdx/client/7.94.3-a4e7c7955b/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/Users/xyz/.local/share/sfdx/client/7.94.3-a4e7c7955b/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/Users/xyz/.local/share/sfdx/client/7.94.3-a4e7c7955b/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/Users/xyz/.local/share/sfdx/client/7.94.3-a4e7c7955b/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/Users/xyz/.local/share/sfdx/client/7.94.3-a4e7c7955b/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/Users/xyz/.local/share/sfdx/client/7.94.3-a4e7c7955b/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (internal/timers.js:461:21)\nOuter stack:\n    at Function.wrap (/Users/xyz/.local/share/sfdx/client/7.94.3-a4e7c7955b/node_modules/@salesforce/core/lib/sfdxError.js:171:27)\n    at PackageInstallCommand.catch (/Users/xyz/.local/share/sfdx/client/7.94.3-a4e7c7955b/node_modules/salesforce-alm/dist/ToolbeltCommand.js:248:46)\n    at async PackageInstallCommand._run (/Users/xyz/.local/share/sfdx/client/7.94.3-a4e7c7955b/node_modules/@salesforce/command/lib/sfdxCommand.js:85:13)\n    at async Config.runCommand (/Users/xyz/.local/share/sfdx/client/7.94.3-a4e7c7955b/node_modules/@oclif/config/lib/config.js:173:24)\n    at async Main.run (/Users/xyz/.local/share/sfdx/client/7.94.3-a4e7c7955b/node_modules/@oclif/command/lib/main.js:27:9)\n    at async Main._run (/Users/xyz/.local/share/sfdx/client/7.94.3-a4e7c7955b/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/Users/xyz/.local/share/sfdx/client/7.94.3-a4e7c7955b/dist/cli.js:114:21)",
  "warnings": []
}
```

**Comment by sinadino-zennify** [comment]
The issue with Alert__c and BillingStatement__c  remains the same for FSC version id: 04t1E000001Irko, wondering what is the work around it.
